FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3-pip python3-dev && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean && \
    ln -s /usr/bin/python3 /usr/bin/python

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
COPY . /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["python", "app.py"]